In [26]:
# Finding unique numbers from the list...
a = [6, 8, 8, 5, 9, 11]
unique = [6, 12, 13, 14]

c=0
for i in range(len(a)):
  for j in range(len(unique)):
    if a[i] == unique[j]:
      c += 1
if c == 0:
  print('Unique')
else:
  print('not unique')
   


not unique


In [27]:
# print even values values in array

import numpy as np
x = [0, 1, 3, 5, 10, 12,  11]
x

for i in x:
  if i % 2== 0:  
    print(i)

0
10
12


In [28]:
#generating 2D array with single loop
import numpy as np
from numpy import random
a = random.randint(11, 85, size =(3,3))
sum =0
r,c =a.shape

print(a)
for i in range(0, r*c):
  row = i //c
  col = i % c
  print(a[row][col])
 

[[63 26 31]
 [69 34 24]
 [59 60 80]]
63
26
31
69
34
24
59
60
80


In [29]:
# Generate a 2D random array .
# use this code with one loop.
# also add sum of upper diagonal elements..

import numpy as np
from numpy import random
random.seed(0)

a = random.randint(11, 85, size =(3,3))
sum =0
r,c =a.shape

for i in range(0, r*c):
  row = i //c
  col = i% c
  if row < col: # lower diagonal is a square matrix
      sum += a[row,col]

print('Random array is :\n\n',a,'\n\n ...and its upper diagonal sum is \n',sum)
      

Random array is :

 [[55 58 75]
 [78 78 20]
 [32 47 81]] 

 ...and its upper diagonal sum is 
 153


In [30]:
# Generating 3D array

import numpy as np
from numpy import random
x = random.randint(100, size =(6, 3, 5))
random.seed(0) # it will generate same random values every time
print(x)

[[[88 88 12 58 65]
  [39 87 46 88 81]
  [37 25 77 72  9]]

 [[20 80 69 79 47]
  [64 82 99 88 49]
  [29 19 19 14 39]]

 [[32 65  9 57 32]
  [31 74 23 35 75]
  [55 28 34  0  0]]

 [[36 53  5 38 17]
  [79  4 42 58 31]
  [ 1 65 41 57 35]]

 [[11 46 82 91  0]
  [14 99 53 12 42]
  [84 75 68  6 68]]

 [[47  3 76 52 78]
  [15 20 99 58 23]
  [79 13 85 48 49]]]


In [31]:
#calculating sum of 3D Array 

# random.seed(0) if the same random numbers are required every time.
import numpy as np
from numpy import random
random.seed(0)
x = random.randint(100, size =(3, 4, 5))

p,r,c = x.shape
sum =0
for i in range(p):
    for j in range(r):
      for k in range(c):
        sum += x[i,j]
    
print('x= \n',x,'\n sum = \n',sum)

x= 
 [[[44 47 64 67 67]
  [ 9 83 21 36 87]
  [70 88 88 12 58]
  [65 39 87 46 88]]

 [[81 37 25 77 72]
  [ 9 20 80 69 79]
  [47 64 82 99 88]
  [49 29 19 19 14]]

 [[39 32 65  9 57]
  [32 31 74 23 35]
  [75 55 28 34  0]
  [ 0 36 53  5 38]]] 
 sum = 
 [2600 2805 3430 2480 3415]


In [32]:
#calculating corresponding mean of 3D Array 

import numpy as np
from numpy import random
random.seed(0)
x = random.randint(100, size =(3, 4, 5))
x


p,r,c = x.shape
mean =random.rand(r, c)
#mean =ones(r, c)

for i in range(r):
    for j in range(c):
      sum = 0
      for k in range(p):
        sum += x[k,i,j]
    avg = sum/p
    mean[i,j] = avg

print('3D array  is: x = \n\n',x,'\n\n and its corresponding mean is: Mean = \n\n',mean)

3D array  is: x = 

 [[[44 47 64 67 67]
  [ 9 83 21 36 87]
  [70 88 88 12 58]
  [65 39 87 46 88]]

 [[81 37 25 77 72]
  [ 9 20 80 69 79]
  [47 64 82 99 88]
  [49 29 19 19 14]]

 [[39 32 65  9 57]
  [32 31 74 23 35]
  [75 55 28 34  0]
  [ 0 36 53  5 38]]] 

 and its corresponding mean is: Mean = 

 [[ 0.22232139  0.38648898  0.90259848  0.44994999 65.33333333]
 [ 0.90234858  0.09928035  0.96980907  0.65314004 67.        ]
 [ 0.35815217  0.75068614  0.60783067  0.32504723 48.66666667]
 [ 0.63427406  0.95894927  0.65279032  0.63505887 46.66666667]]


In [33]:
print(np.mean(x,axis=1))
print('\n',np.mean(x,axis=0))

[[47.   64.25 65.   40.25 75.  ]
 [46.5  37.5  51.5  66.   63.25]
 [36.5  38.5  55.   17.75 32.5 ]]

 [[54.66666667 38.66666667 51.33333333 51.         65.33333333]
 [16.66666667 44.66666667 58.33333333 42.66666667 67.        ]
 [64.         69.         66.         48.33333333 48.66666667]
 [38.         34.66666667 53.         23.33333333 46.66666667]]


In [34]:
x = [3, 'AA', 60, 90.1, 55, '6l']
item = 55
flag = 0

for i in range(len(x)): # for i in x, if item == i
  if item == x[i]:
    flag =1
    break

if flag ==1:
  print('Item exit in a list at location  ' + str(i))
else:
   print('Item does not exit')

Item exit in a list at location  4


In [35]:
def function():
    x = 10
    function()

In [36]:
#recursive funtions in python
def countdown(n):
  print(n, end = ' ')
  if n == 0:
    return             # Terminate recursion
  else:
    countdown(n - 1)   # Recursive call

In [37]:
countdown(5)

5 4 3 2 1 0 

In [38]:
#list comprehension
list_a = []
for i in range(0, 10):
  if i %2 ==0:
    list_a.append(i**2)
print(list_a, end = ' ')

[0, 4, 16, 36, 64] 

In [39]:
#list comprehension

list_b = [i**2 for i in range(0, 10) if i%2 ==0]   #[expression for item in list if conditional]
print(list_b, end = ' ')

[0, 4, 16, 36, 64] 

In [40]:
list_a = [1, 3, 6, 9, 12, 15]
list_b = []
for number in list_a:
    if number % 4 == 0:
        list_b.append(number)

print(list_b)

[12]


In [41]:
list_a = [1, 3, 6, 9, 12, 15]
list_b = [number for number in list_a if number % 4 == 0]

print(list_b)

[12]


In [42]:
comp = [i**2 for i in range(5)] #if i//3 == 0]

print(comp)

[0, 1, 4, 9, 16]


In [43]:
comp = [i**2 for i in range(5) if i %2 == 0]

print(comp)

[0, 4, 16]


In [44]:
# Without using lambdas
def starts_with_A(s):
    return s[0] == "A"

fruit = ["Apple", "Banana", "Pear", "Apricot", "Orange"]
map_list = list(map(starts_with_A, fruit))

print(map_list)
starts_with_A(fruit)

[True, False, False, True, False]


False

In [45]:
# Without using lambdas
def starts_with_A(s):
    return s[0] == "A"

fruit = ["Apple", "Banana", "Pear", "Apricot", "Orange"]
map_list = list(filter(starts_with_A, fruit))

print(map_list)
#starts_with_A(fruit)

['Apple', 'Apricot']


In [46]:
fruit = ["Apple", "Banana", "Pear", "Apricot", "Orange"]
map_object = map(lambda s: s[0] == "A", fruit)

print(list(map_object))

[True, False, False, True, False]


In [47]:
for i in map_object:
  print(list(i))

In [48]:
for value in map_object:
    print(value)

In [51]:
def squares(j):
  print(j**2)
squares(j)

0


In [52]:
print(print(j))

0
None


In [53]:
y =lambda x: x**2
x = [0, 2, 3, 5, 6]
y(3)

9

In [54]:
z=[1, 2, 3, 0,0.9]
fil_map = list(map(lambda x: x==2 or x==3, z))
fil = list(filter(lambda x: x==2 or x==3 ,z))

print(fil_map,'\n', fil)
print()

[False, True, True, False, False] 
 [2, 3]



In [56]:
# function that filters vowels
def fun(variable):
    letters = ['a', 'e', 'i', 'o', 'u']
    if (variable in letters):
        return True
    else:
        return False
    
# sequence
sequence = ['g', 'e', 'e', 'j', 'k', 's', 'p', 'r']
  
# using filter function
filtered = filter(fun, sequence)

print(list(filtered))
  
#print('The filtered letters are:')
#for s in filtered:
#    print(s)

['e', 'e']


In [57]:
s = ['g', 'e', 'e', 'j', 'k', 's', 'p', 'r']
filtering = list(filter(lambda l:l==['a', 'e', 'i', 'o', 'u'],s))

print(filtering)

[]


In [58]:
# function that filters vowels
def fun(variable):
    letters = ['a', 'e', 'i', 'o', 'u']
    if (variable in letters):
        return True
    else:
        return False
    
# sequence
sequence = ['g', 'e', 'e', 'j', 'k', 's', 'p', 'r']

fun(sequence) 
# using filter function
#filtered = filter(fun, sequence)

#print(list(filtered))
  
#print('The filtered letters are:')
#for s in filtered:
#    print(s)

False

In [59]:
# a list contains both even and odd numbers. 
seq = [0, 1, 2, 3, 5, 8, 13]
  
# result contains odd numbers of the list
result = filter(lambda x: x % 2 != 0, seq)
print(list(result))
  
# result contains even numbers of the list
result = filter(lambda x: x % 2 == 0, seq)
print(list(result))

[1, 3, 5, 13]
[0, 2, 8]


In [60]:
import functools

def mult(x,y):
    #print("x=",x," y=",y)
    return x*y

fact=functools.reduce(mult, range(1, 2))
print ('Factorial of 3: ', fact)


Factorial of 3:  1


In [61]:
from functools import reduce
# Returns the sum of all the elements using `reduce`
result = reduce((lambda a, b: a + b), [1, 2, 3, 4])
print(result)

10


In [62]:
from functools import reduce
# Returns the sum of two elements
def sumTwo(a,b):
    return a+b
random.seed(0)

a = [random.randint(0,100) for i in range(100)]
result = functools.reduce(sumTwo, a)
print(result)

4823


In [63]:
import random
a=[]
for i in range(0,10):
  #a = random.randint(0,100)
  a.append(random.randint(0,100))
print(a)

[5, 35, 71, 87, 77, 11, 84, 72, 90, 54]


In [64]:
a =[random.randint(0,100) for i in range(10)]
print(a)

[58, 25, 23, 72, 92, 84, 35, 27, 0, 23]


In [65]:
def get_alphabets(character):
    alphabets = [chr(i) for i in range(97, 123) if i!= character]
    return tuple(alphabets)
get_alphabets(99)

('a',
 'b',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z')

In [69]:
NumStd = int(input('How many student you record: '))
stdlst =[]

def func(user):
  if user[1] >= 25:
    return [user[0] + ' above 25', user[1]]
  else:
    return [user[0] + ' under 25', user[1]]

for i in range(NumStd):
  std =input('Enter Student Name: ')
  age =int(input('Enter age: '))
  stdlst.append([std, age])

res =map(func,stdlst)
print(stdlst)
print(list(res))

How many student you record: 2
Enter Student Name: Rafay
Enter age: 22
Enter Student Name: Bensu
Enter age: 23
[['Rafay', 22], ['Bensu', 23]]
[['Rafay under 25', 22], ['Bensu under 25', 23]]


In [70]:
stdlst

[['Rafay', 22], ['Bensu', 23]]