In [42]:
print('practice python basic programs ')

practice python basic programs 


In [43]:
#practice  questions:

a= [1, 2, 3, 4, 5, 6, 7]
for i in range(0, 7):
  print(a[i])

1
2
3
4
5
6
7


In [44]:
a= [1, 2, 3, 4, 5, 6, 7]
for i in range(0, 7):
  print(a[i], end = '\n')

1
2
3
4
5
6
7


In [45]:
a= [1, 2, 3, 4, 5, 6, 7]
for i in range(0, 7):
  print(a[i], end = ' ') # modifying output, putting it in one row

1 2 3 4 5 6 7 

In [46]:
print(a[0])

1


In [47]:
a[5] ='BB'

In [49]:
a

[1, 2, 3, 4, 5, 'BB', 7]

In [50]:
a[0] = [1, 2, 3, 4, 5] # assiging nested list

In [51]:
a

[[1, 2, 3, 4, 5], 2, 3, 4, 5, 'BB', 7]

In [52]:
for i in range(0, 7):
  print(a[i], end = ' ')

[1, 2, 3, 4, 5] 2 3 4 5 BB 7 

In [53]:
a[1]

2

In [54]:
x =range(0, 6)

In [55]:
x

range(0, 6)

In [56]:
print(x)

range(0, 6)


In [57]:
range(6)

range(0, 6)

In [58]:
len(a)

7

In [59]:
a

[[1, 2, 3, 4, 5], 2, 3, 4, 5, 'BB', 7]

In [60]:
y = [2, 6, 9, 'abc', 5, 'xyz']

for i in range(len(y)):
  print(y[i], end =' ')

2 6 9 abc 5 xyz 

In [62]:
y.reverse()
y

['xyz', 5, 'abc', 9, 6, 2]

In [63]:
x = ['xyz', 5, 'abc', 9, 6, 2, 'suleman']


In [64]:
x.reverse()

In [65]:
x

['suleman', 2, 6, 9, 'abc', 5, 'xyz']

In [66]:
x= ['suleman', 2, 6, 9, 'abc', 5, 'xyz']
for i in range(-1, -8, -1):
  print(x[i], end = ' ')

xyz 5 abc 9 6 2 suleman 

In [67]:
x= ['suleman', 2, 6, 9, 'abc', 5, 'xyz']
for i in range(len(x)):
  print(x[i], end = ' ')

suleman 2 6 9 abc 5 xyz 

In [68]:
x= ['suleman', 2, 6, 9, 'abc', 5, 'xyz']
for i in range(-7, -1, -1):
  print(x[i], end = ' ')

In [69]:
x= ['suleman', 2, 6, 9, 'abc', 5, 'xyz']
for i in range(6, -1, -1):
  print(x[i], end = ' ')

xyz 5 abc 9 6 2 suleman 

In [70]:
x= ['suleman', 2, 6, 9, 'abc', 5, 'xyz']
for i in range(-1, -2, -1):
  print(x[i], end = ' ')

xyz 

# write a python code for finding min, max using list

In [71]:
# Finding minimum numbers from the list...
a = [6, 8, 5, 9, 11]
minIndex = 0

for i in range(len(a)):
  if a[minIndex] > a[i]:
    minIndex = i

print(a[minIndex])


# Finding maximum numbers from the list...
a = [6, 8, 5, 9, 11]
maxIndex = 0

for i in range(len(a)):
  if a[maxIndex] < a[i]:
    maxIndex = i

print(a[maxIndex])

5
11


# Generating random numbers...

In [75]:
import random
random_list = []
random.seed(0) # it will generate same random numbers every time...

for i in range(10):
  n = random.randint(1, 100)
  random_list.append(n)

print(random_list)

[50, 98, 54, 6, 34, 66, 63, 52, 39, 62]


In [76]:
import random
list_g =[]
# random.seed(0)
for i in range(20):
  rand = random.randint(1, 1000)
  list_g.append(rand)

print(list_g)

[367, 598, 914, 930, 224, 517, 143, 289, 144, 774, 98, 634, 819, 257, 932, 546, 723, 830, 617, 924]


# Sorting algorithm
 01 Bubble sort, 
 02 Selection Sort, 
 03 Insertion Sort, 
 04 Merge Sort, 
 05 Quick Sort.

In [77]:
# Bubble Sort...
# ascending order of numbers

import random 
random.seed(0)
x = []

for k in range(20):
  x.append(random.randint(1, 100))
print(x)

for i in range(len(x)-1):
  for j in range(len(x)-1):
    if x[j] > x[j+1]:
      temp = x[j]
      x[j] = x[j+1]
      x[j+1] = temp
print(x)

[50, 98, 54, 6, 34, 66, 63, 52, 39, 62, 46, 75, 28, 65, 18, 37, 18, 97, 13, 80]
[6, 13, 18, 18, 28, 34, 37, 39, 46, 50, 52, 54, 62, 63, 65, 66, 75, 80, 97, 98]


In [78]:
# Bubble Sort...
# Descending order of numbers

import random 
random.seed(0)
x = []

for k in range(20):
  x.append(random.randint(1, 100))
print(x)

for i in range(len(x)-1):
  for j in range(len(x)-1):
    if x[j] < x[j+1]:
      temp = x[j]
      x[j] = x[j+1]
      x[j+1] = temp
print(x)

[50, 98, 54, 6, 34, 66, 63, 52, 39, 62, 46, 75, 28, 65, 18, 37, 18, 97, 13, 80]
[98, 97, 80, 75, 66, 65, 63, 62, 54, 52, 50, 46, 39, 37, 34, 28, 18, 18, 13, 6]


# Numpy Array Sort (Selection)

In [79]:
# selection Sort...
# Descending order of numbers

import random 
random.seed(0)
x = []

for k in range(20):
  x.append(random.randint(1, 100))
print(x)


for i in range(len(x)):
  minIndex =i
  for j in range(i+1,len(x)):
    if x[j] < x[minIndex]:
      minIndex =i
      temp = x[j]
      x[j] = x[minIndex]
      x[minIndex] = temp
print(x)

[50, 98, 54, 6, 34, 66, 63, 52, 39, 62, 46, 75, 28, 65, 18, 37, 18, 97, 13, 80]
[6, 13, 18, 18, 28, 34, 37, 39, 46, 50, 52, 54, 62, 63, 65, 66, 75, 80, 97, 98]


In [80]:
# selection Sort using functions
# Descending order of numbers

import random 
random.seed(0)
x = []

for k in range(20):
  x.append(random.randint(1, 100))
print(x)

def ascend_f(x):
  for j in range(0, len(x)):
    minIndex =j
    for i in range(j+1, len(x)):
      if x[i] < x[minIndex]:
        minIndex =j
        temp = x[i]
        x[i] = x[minIndex]
        x[minIndex] = temp
  print(x)  

ascend_f(x)

[50, 98, 54, 6, 34, 66, 63, 52, 39, 62, 46, 75, 28, 65, 18, 37, 18, 97, 13, 80]
[6, 13, 18, 18, 28, 34, 37, 39, 46, 50, 52, 54, 62, 63, 65, 66, 75, 80, 97, 98]


In [81]:
for i in range(5):
  for j in range(3):
    print(' IBA ', end ='')

 IBA  IBA  IBA  IBA  IBA  IBA  IBA  IBA  IBA  IBA  IBA  IBA  IBA  IBA  IBA 

In [82]:
#you cannot directly assgin values to list,
#you first need to create empy list first.
x = []

x.append('pakistan')  # but not  x[0] = 'pakistan,      it will give you error
                      # But this can happend in dictionary 
x[0]

'pakistan'

In [83]:
#y ={}
y[0] = 'Pakistan'

y

['Pakistan', 5, 'abc', 9, 6, 2]

# Numpy (Data Structure)

In [84]:
import numpy as np
x = np.array([1, 3, 5, 10, 11])

x

array([ 1,  3,  5, 10, 11])

In [85]:
y = np.array([[1, 5, 9],
             [2, 8, 3],
             [5, 9, 6]])


In [86]:
y

array([[1, 5, 9],
       [2, 8, 3],
       [5, 9, 6]])

In [87]:
y[1][2]

3

In [88]:
y[1]

array([2, 8, 3])

In [89]:
y.shape # gives dimentions

(3, 3)

In [90]:
x.shape

(5,)

In [91]:
# print even index values in array

import numpy as np
x = np.array([1, 3, 5, 10, 11])
x

for i in range(0,len(x), 2):
  print(x[i])

1
5
11


In [92]:
# print even values values in array

import numpy as np
x = np.array([1, 3, 5, 10, 11])
x

for i in range(0, len(x)):
  if x[i] % 2==0:
    print(x[i])

10


In [93]:
x

array([ 1,  3,  5, 10, 11])

In [94]:
for i in x:
  print(x)

[ 1  3  5 10 11]
[ 1  3  5 10 11]
[ 1  3  5 10 11]
[ 1  3  5 10 11]
[ 1  3  5 10 11]


In [95]:
for i in range(len(x)):
  print(x)

[ 1  3  5 10 11]
[ 1  3  5 10 11]
[ 1  3  5 10 11]
[ 1  3  5 10 11]
[ 1  3  5 10 11]


# sum of 2D array



In [97]:
# commulative sum of 2D array

import numpy as np
from numpy import random
random.seed(0) # it will give the same random number every time.

a = random.randint(11, 85, size =(3,5))
sum =0
r,c =a.shape

for i in range(0,r):
  for j in range(0,c):
    sum = sum + a[i][j] #  also == sum = sum + a[i,j]

print(sum)

847


In [98]:
a

array([[55, 58, 75, 78, 78],
       [20, 32, 47, 81, 23],
       [69, 76, 50, 57, 48]])

In [99]:
# Generate a 2D random array which prints only those data whose index sum is odd.

import numpy as np
from numpy import random
random.seed(0)

a = random.randint(11, 85, size =(3,5))

r,c =a.shape
for i in range(r):
  for j in range(c):
    if (i+j) %2 !=0:
      print(a[i][j])

    

58
78
20
47
23
76
57


In [101]:
# concatenation of two arrays

import numpy as np
from numpy import random
random.seed(0)

a = random.randint(100, size =(2,3))
b = random.randint(100, size =(2,3))

print(a)
print(b)

arr = np.concatenate((a,b))
print(arr)

[[44 47 64]
 [67 67  9]]
[[83 21 36]
 [87 70 88]]
[[44 47 64]
 [67 67  9]
 [83 21 36]
 [87 70 88]]


In [102]:
# concatenation of two arrays

import numpy as np
from numpy import random
random.seed(0)

a = random.randint(100, size =(2,3))
b = random.randint(100, size =(2,3))

print(a)
print(b)

arr = np.concatenate((a,b), axis =1) # axis = 1
print(arr)

[[44 47 64]
 [67 67  9]]
[[83 21 36]
 [87 70 88]]
[[44 47 64 83 21 36]
 [67 67  9 87 70 88]]


In [104]:
# concatenation of two arrays

import numpy as np
from numpy import random
random.seed(0)

a = random.randint(100, size =(2,3))
b = random.randint(100, size =(2,3))

print(a)
print(b)

arr = np.concatenate((a,b), axis =0)  # axis = 0
print(arr)

[[44 47 64]
 [67 67  9]]
[[83 21 36]
 [87 70 88]]
[[44 47 64]
 [67 67  9]
 [83 21 36]
 [87 70 88]]


In [105]:
name = 'Rafay'

for i in name:
  print(name)

Rafay
Rafay
Rafay
Rafay
Rafay


In [106]:
#reverse the characters by using splicing function...

name = name[::-1] # printing output using splicing
print(name)

yafaR


In [107]:
for i in range(4, -1, -1):
  print(name[i])

R
a
f
a
y


In [108]:
name = 'Rafay'
for i in range(0, 5):
  if name[i].islower():
    print(name.upper(), end = ' ')
  else:
    print(name.lower(), end = ' ')

rafay RAFAY RAFAY RAFAY RAFAY 

In [109]:
name = 'Rafay'
for i in range(0, 5):
  if name[i].islower():
    print(name[i].upper(), end = ' ')
  elif name[i].isupper():
    print(name[i].lower(), end = ' ')

r A F A Y 

In [110]:
#spilting arrays in different sizes
arr = [1, 2, 3, 4, 5, 6]

newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [111]:
#spilting arrays in different sizes
arr = [1, 2, 3, 4, 5, 6]

newarr = np.array_split(arr, 5)
print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [112]:
# searching elements in an array 
# and print their indices...

arr_ind =[]  # like where function 
search_elem = 4
arr =[1, 2, 3, 4, 5, 4, 4]
for i in range(len(arr)):
  if arr[i] == search_elem:
    arr_ind.append(i)
print(arr_ind)

[3, 5, 6]


In [113]:
# searching elements in an array 
# and print their indices...
# like where function 

def mysearch(arr, search_elem):
  arr_ind =[] 
  for i in range(len(arr)):
    if arr[i] == search_elem:
      arr_ind.append(i)
  print(arr_ind)

In [114]:
mysearch(arr,search_elem)

[3, 5, 6]
